### ISSUE TITLE
Package is broken in 7_6_0...

### ISSUE THREAD

**Issue by ajgilbert** [ajgilbert/ICHiggsTauTau#105]
... and I mean **really** broken:

 - [x] this doesn't compile anymore:

          edm::RefToBaseProd<T> reftobase = edm::RefToBaseProd<T>((handle->refAt(0)));

- [x] we are now forced to use the `edm::consumes` mechanism. Info [here](https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3428/1.html) and [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent#Consumes_and_Helpers). This isn't available in 5_3_X so will need some sort of workaround - ideally without a huge amount of #ifdef'ing. 
- [ ] Need to check if CMSSW producers work ok in [multi-threaded mode](https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedAnalysisEDAnalyzer). *Is this enabled by default?*

**Comment by adewit** [comment]
Oh I love change! :-|
For the edm::RefToBaseProd, presumably this tries to explain why it won't compile anymore:
"The design which allowed a RefToBaseProd to be constructed from an
edm::Ref or RefToBase caused problems for future changes (edm::View
and slimming). Given this was equivalent to taking an arbitrary pointer
and then obtaining which std::vector<> the data is stored in, we
determined this was not an absolute requirement."
Are they trying to say we can basically do the arbitrary-pointer-taking etc. ourselves, do some more magic and create an edm::RefToBaseProd from a handle?
And re the multi threaded mode - this wouldn't work with crab, right? So hoping it's off by default?

**Comment by ajgilbert** [comment]
So this thing is mostly hitting us where we try to fill a ValueMap from an edm::View, where we don't know if the View points to a regular vector or a vector or Refs. If it's the latter then just using the handle will give us the wrong product ID for the ValueMap - it gives us the ID of the vector of Refs, not the original vector the Refs point to. You end up with a broken ValueMap. 

What we're doing to get around this with the RefToBaseProd is a bit of a hack, so I'm not that surprised they removed it. Strictly we don't need a RefToBaseProd though - so if we can't find another way to construct it with the correct product ID we can try something else.

About the multi-threaded - yes probably not allowed by crab yet, and it might be there's no significant performance hit anyway.

**Comment by adewit** [comment]
More broken things!
"fromPV" (as used here https://github.com/ajgilbert/ICHiggsTauTau/blob/master/test/higgstautau_cfg_74X_Sep15.py#L262) crashes in 7_6. I suspect this is the culprit: https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/DataFormats/PatCandidates/interface/PackedCandidate.h#L427 though am not sure - need to investigate more.

**Comment by adewit** [comment]
Ignore me, it doesn't actually crash. Turns out running on the right sample is generally a good idea :-)
