### ISSUE TITLE
Large number of SVFit jobs with new workflow

### ISSUE THREAD

**Issue by rcl11** [ajgilbert/ICHiggsTauTau#109]
For @ajgilbert and @adewit, it is clear that the number of events in the output trees is now a lot larger than it was in Run 1, due to moving cuts like isolation to post output tree. This poses a problem for our SVfit workflow, which currently requires more than 10 000 jobs for the full set of MC samples (if I use 7000 events per job, which I think was what we had in Run 1 and still makes the jobs several hours long), which is only going to get larger as we add the exclusive samples. The question is whether we have to live with this and we simply risk having to wait longer for SVFit jobs (given that so many of our cuts are now at ntuple level, in principle we could have to run this less often, although this has not necessarily reflected reality so far with the fairly frequent changes of triggers and other pre-output ntuple level choices), or whether there could be value to altering our workflow to apply some preselection and only run the calculation for a subset of the events in the tree (and when creating the tree, fill the SVFit mass branch with -999 for the events for which there is no calculation). Thoughts? Experiences of trying to get >10000 jobs of that length through any kind of batch system?

**Comment by adewit** [comment]
Current "solution" (all those grid nodes were just sitting around doing nothing anyway, right?) here: https://github.com/adewit/ICSVFit 
Setup probably not optimal (could do with splitting the jobs across a few tasks, and even increasing nevents/job as we're now not tied to the 8hrs of the medium queue), also there's a lot of code duplication now but this will be refined later
