### ISSUE TITLE
Need to rename Analysis/*/data directories

### ISSUE THREAD

**Issue by ajgilbert** [ajgilbert/ICHiggsTauTau#17]
We currently store various root files and inputs that are needed for the analyses here (JEC files, mva trainings etc). Unfortunately it turns out that crab scans recursively for any directory named data under $CMSSW_BASE/src and ships this off with each job. This wastes storage space and time packing and sending these files to the crab server. I suggest we rename the folder from "data" to "input" to avoid this

**Comment by rcl11** [comment]
Closed by #32
