### ISSUE TITLE
HTTSequence doesn't run old trigger filter mode for previous analyses

### ISSUE THREAD

**Issue by adewit** [ajgilbert/ICHiggsTauTau#171]
Just noticed that the trigger filter module is currently always run after HTTPairSelector which isn't in line with the method used for previous analyses. Should remember to add the module to be run t before the pair selector for mssmspring16 and fall15 strategies.

**Comment by danielwinterbottom** [comment]
yeah i wasn't sure if this should be under option or not. Should I do this or is it more just something to keep in mind if we want to run  old strategys again?

**Comment by adewit** [comment]
Just something to keep in mind - that's why I self-assigned instead of doing it straight away ;-)

**Comment by adewit** [comment]
Fixed by https://github.com/ajgilbert/ICHiggsTauTau/commit/08161da173baaca6d8c16940182e3c31483b621b
