### ISSUE TITLE
Re-integrate the electron conversion veto flag into this package

### ISSUE THREAD

**Issue by ajgilbert** [ajgilbert/ICHiggsTauTau#24]
It is currently calculated and provided (as a ValueMap) by this external package: https://github.com/ajgilbert/ICAnalysis-ElectronConversionCalculator

At the time this was due to compiler problems in CMSSW_4_X_Y and early CMSSW_5_X_Y releases. 

Someone should check:
 - if the two plugins defined in this package compile ok in our current supported releases
 - If not, can we use the `#if CMSSW_MAJOR_VERSION >= X` preprocessor checks to work around this
 - Is there a new definition/algorithm for the conversion veto in CMSSW_7_X_Y for run 2? If so, this should be added as a new plugin that produces a ValueMap in the same format.
   * Related to this: check how this is calculated in PAT/MINIAOD in 7_3_X/7_4_X and make sure we know how to produce it consistently in AOD directly on the gedGsfElectrons
 - Is there a possibility to re-calculate on the level of miniAOD? (probably not, but worth knowing)

**Comment by adewit** [comment]
This compiles fine in CMSSW_7_2_0, and the definition of the conversion veto hasn't changed in CMSSW 7. It can be recalculated from miniAOD using the slimmedElectrons and reducedEgamma:reducedConversions.

Remaining checks:
- (Compilation in other CMSSW_7X releases)
- Consistency of all calculation methods (recalculation in miniAOD <-> value stored in miniAOD on a full sample/value stored in miniAOD <-> calculation in AOD on a full sample)

**Comment by ajgilbert** [comment]
Code is now re-added by PR #36. it still remains to test that recalculating on miniAOD gives the same result as what's already stored

**Comment by adewit** [comment]
Calculating on AOD gives the same result as recalculating on miniAOD, and the recalculation on miniAOD comes out the same as the value already stored:
![electronconversion_aodvsminiaod_abs](https://cloud.githubusercontent.com/assets/5803497/7560188/110f2db8-f7c1-11e4-890b-f63d0db48819.png)
![electronconversion_calculatedvsstored_abs](https://cloud.githubusercontent.com/assets/5803497/7560189/11117fd2-f7c1-11e4-8127-5bd7c00f281d.png)
