### ISSUE TITLE
Update ICMuonProducer to ensure we store all the variables needed to run the Muon ID at ntuple level

### ISSUE THREAD

**Issue by pjdunne** [ajgilbert/ICHiggsTauTau#26]
In run I we implemented the muon ID by storing in the ntuples all the variables used and then having a function in FnPredicates which implemented the ID. This now needs to be updated to the run II ID.

**Comment by ajgilbert** [comment]
Does anyone know how many variables we are missing for the new ID working points? And actually have the old working points changed (in particular MuonTight)?

**Comment by pjdunne** [comment]
Looking at it now, to implement the new "medium" ID which is listed as the baseline one for HTauTau we need in addition to what we have already:
muon.combinedQuality().chi2LocalPosition
muon.combinedQuality().trkKink
muon.innerTrack()->validFraction()
muon.segmentCompatibility()

I'm in the process of adding them at the moment. I haven't checked the loose and tight working points yet.
