### ISSUE TITLE
Treatment of GenParticles in miniAOD

### ISSUE THREAD

**Issue by ajgilbert** [ajgilbert/ICHiggsTauTau#34]
Have to deal with two separate collections:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD#MC_Truth

The prunedGenParticles are a normal reco::GenParticle collection and should contain everything we need in the analysis (matrix element, full tau chain decay, final state electrons/muons). We can just save this as normal with ICGenParticleProducer.

The packedGenParticles are the new pat::PackedGenParticle type and contain all status 1 up to some high rapidity value, and are mainly for clustering gen jets.

### Plan A:
 -  Would like to be able to produce an ic::GenParticle from a PackedGenParticle. Can either template ICGenParticleProducer on the type, or write a brand new producer
 -  As pointed out on the miniAOD twiki some care must be taken with following mother/daughter relations that span the two collections. Currently it wouldn't be possible to do this is we saved two separate ic::GenParticle collections. So if we want to be able to do this have to come up with a recipe - possibly trying to merge the two collections into one before we write it

### Plan B:
 - decide we don't care about the packedGenParticles at all in the analysis and don't bother with any of this

**Comment by pjdunne** [comment]
Hi, one use case that we have for the gen particles quite frequently is to look for missed leptons. The description of the prunedGenParticles doesn't make clear whether these will be included there yet. If they aren't then we at least would probably need to work on plan A.

**Comment by ajgilbert** [comment]
You can see exactly what is kept here:

https://github.com/cms-sw/cmssw/blob/CMSSW_7_2_X/PhysicsTools/PatAlgos/python/slimming/prunedGenParticles_cfi.py

This line: `"++keep abs(pdgId) == 11 || abs(pdgId) == 13 || abs(pdgId) == 15"` should ensure all the leptons are kept. One thing to bear in mind is that they seem to be changing this definition fairly often, e.g. in 7_5_X: https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/PhysicsTools/PatAlgos/python/slimming/prunedGenParticles_cfi.py

**Comment by pjdunne** [comment]
In which case as long as they remain being kept, and as it looks like b quarks are kept as well we'd probably be ok with just using the packed genparticles to make gen jets
