### ISSUE TITLE
No way to rerun PU jet ID MVA for non CHS jets

### ISSUE THREAD

**Issue by pjdunne** [ajgilbert/ICHiggsTauTau#35]
In CMSSW_7_2_X there is no way to rerun the PU jet ID MVA on jet collections reclustered by the user. This is being fixed in CMSSW_7_4_X and we should remember to fix this.

**Comment by adewit** [comment]
This indeed works in CMSSW 74. Rerunning the MVA on reclustered ak4 CHS jets sometimes gives the same mva value as is stored in the slimmedJets collection while sometimes being way off - needs more investigation.

**Comment by adewit** [comment]
I'm on a rollllllll! It all looks much better when using... well, exactly what goes into the miniAOD (see https://github.com/cms-sw/cmssw/blob/d7d8b2b4ee29a2fdad37e1153eb7b4e21e84019f/RecoJets/JetProducers/test/testJetTools_cfg.py#L80-L89)
