### ISSUE TITLE
Daughters and status codes in new MC have changed

### ISSUE THREAD

**Issue by pjdunne** [ajgilbert/ICHiggsTauTau#50]
The new pythia 8 status codes don't provide a direct replacement for status 3. The new status 21-29 is similar, but differs in that the lepton from a W->lnu decay for instance isn't always status 21-29. 

I've emailed Josh Bendavid to ask if there is a recommendation, and it also appears from slides from Gen group meetings in early May that they are preparing a new set of "status flags" to try and solve this issue.

**Comment by ajgilbert** [comment]
Dumping some info that might be useful:
http://home.thep.lu.se/~torbjorn/pythia81html/ParticleProperties.html
https://hypernews.cern.ch/HyperNews/CMS/get/generators/2632.html?inline=-1
https://hypernews.cern.ch/HyperNews/CMS/get/generators/2630.html?inline=-1
https://hypernews.cern.ch/HyperNews/CMS/get/generators/2629.html?inline=-1

From this it seems like a status 23 (matrix-element) charged lepton would always be created, but if there's no FSR added then the status 23 is removed and replaced directly with a status 1 copy.

**Comment by adewit** [comment]
I think this can be closed as we've all switched to using the status flags now
