### ISSUE TITLE
ICGenParticlePruner doesn't copy status flags

### ISSUE THREAD

**Issue by pjdunne** [ajgilbert/ICHiggsTauTau#82]
@adewit @rcl11 While working with the new status flags I found that our ICGenParticlePruner doesn't keep the status flag information. The ICGenParticlePruner seems to be a copy of an older version of the cmssw GenParticlePruner, the new version of which does keep the status flags. I've switched from ICGenParticlePruner to GenParticlePruner in my config and not seen any issues.

**Comment by adewit** [comment]
@ajgilbert was there a reason for copying the official GenParticlePruner into ICHiggsTauTau (other than making sure the same version of this module was used even when switching CMSSW versions)?

**Comment by ajgilbert** [comment]
I think I wanted to fix this bug: https://github.com/cms-sw/cmssw/commit/0647a8f68049ade2c7a21a0888609b26925ebe54, before the fix actually made it into the release. So for recent 7_X_Y releases it should be fine to just take the official one, but 5_3_X was [never patched](https://github.com/cms-sw/cmssw/blob/CMSSW_5_3_X/PhysicsTools/HepMCCandAlgos/plugins/GenParticlePruner.cc#L261), so could be worth keeping it around, maybe renaming the plugin as GenParticlePruner53X to avoid any confusion in the future.

**Comment by adewit** [comment]
Aha, makes sense. Yes should probably keep it just in case, I'll take care of renaming the plugin.
